Notebook til test af små kode-bidder.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
n=10
[int(0.35*n), int(0.7*n)]

[3, 7]

In [10]:
n_samples=5
noise=0.5
X = np.linspace(-3, 3, num=n_samples).reshape(-1,1) # 1-D
np.random.shuffle(X)
y = np.random.normal((0.5*np.sin(X[:,0]*3) + X[:,0]), noise)

In [11]:
y

array([-4.23128949, -1.16372675,  1.54108117, -1.13588619,  1.30903777])

In [13]:
X

array([[-3. ],
       [ 0. ],
       [ 3. ],
       [-1.5],
       [ 1.5]])

In [14]:
data_set = np.vstack((X.T,y)).T

In [15]:
data_set

array([[-3.        , -4.23128949],
       [ 0.        , -1.16372675],
       [ 3.        ,  1.54108117],
       [-1.5       , -1.13588619],
       [ 1.5       ,  1.30903777]])

In [16]:
data_set[:,:-1]

array([[-3. ],
       [ 0. ],
       [ 3. ],
       [-1.5],
       [ 1.5]])

In [17]:
data_set[:,-1]

array([-4.23128949, -1.16372675,  1.54108117, -1.13588619,  1.30903777])

In [18]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x[2:5]

array([2, 3, 4])

In [25]:
x[:-7]

array([0, 1, 2])

In [28]:
x[0:9:2]

array([0, 2, 4, 6, 8])

In [29]:
y = np.arange(35).reshape(5,7)

In [30]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [33]:
y[0:5:2,::2]

array([[ 0,  2,  4,  6],
       [14, 16, 18, 20],
       [28, 30, 32, 34]])

In [11]:
for i in range(10):
    print('text %-12i%-12i' % (10 ** i, 20 ** i))

text 1           1           
text 10          20          
text 100         400         
text 1000        8000        
text 10000       160000      
text 100000      3200000     
text 1000000     64000000    
text 10000000    1280000000  
text 100000000   25600000000 
text 1000000000  512000000000


In [21]:
def printsomething(n=0):
#    for i in range(5):
        print('this is the number: %i' % (n))

printsomething(5)

this is the number: 5


In [14]:
def record_score(name, score=0):
     print('%s scored %s' % (name, score))
        
record_score('Jill', 4)

Jill scored 4


In [3]:
n=3
if n==0:
    print('n is 0')
elif n==1:
    print('n is 1')
else:
    print('n is something else...')

n is something else...


In [2]:
A=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.einsum('ii -> i', A)

array([1, 5, 9])